CREATE TABLE IF NOT EXISTS `ryoaki_app`.`trip` (
  `trip_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id`  INT(11) NOT NULL,
  `driver_id`  INT(11) NOT NULL,
  `ride_type_id` INT(11) NOT NULL,
  `dispatcher_id` INT(11) NULL DEFAULT NULL,
  `payment_id`  INT(11) NULL DEFAULT NULL,
  `pick_up_address` VARCHAR(255) NOT NULL,
  `destination_address` VARCHAR(255) NOT NULL,
  `trip_status` VARCHAR(50) NOT NULL,
  `trip_start_dttm` DATETIME NOT NULL,
  `trip_completed_dttm` DATETIME NOT NULL,
  `booking_origination` VARCHAR(10) NOT NULL,
  `estimated_fare_amount_val` DATETIME NOT NULL,
  `actual_fare_amount_val` INT(11) NOT NULL,
  `created_by_user_id` INT(11) NOT NULL,
  `created_dttm` DATETIME NOT NULL,
  `modified_by_user_id` INT(11) NOT NULL,
  `modified_dttm` DATETIME NOT NULL,
  PRIMARY KEY (`trip_id`),
  UNIQUE INDEX `trip_id_UNIQUE` (`trip_id` ASC),
ENGINE = InnoDB;
